kind: BuildConfig
apiVersion: v1
metadata:
  name: demo-root-build
spec:
  source:
    contextDir: s2i-root
    git:
      uri: https://github.com/adambkaplan/s2i-assemble-user-demo.git
  strategy:
    dockerStrategy: {}
  output:
    to: 
      kind: ImageStreamTag
      name: s2i-root:latest